### ISSUE TITLE
Fail to do Fanin after fanout in z9264 platform

### ISSUE THREAD

**Issue by waliulislam** [open-switch/opx-nas-interface#83]
```
root@OPX:~#  opx-config-hybrid-group set hybrid-group profile --name hybrid-group-13 --profile restricted
Namespace(command='set', config='profile', name='hybrid-group-13', profile='restricted', subcommand='hybrid-group')
e101-025-0
Success
Key: 1.19.1245192.
base-if-phy/hardware-port/front-panel-port = 25
if/interfaces/interface/name = e101-025-0
if/interfaces/interface/type = ianaift:ethernetCsmacd
cps/object-group/return-code = 0
base-if-phy/hardware-port/subport-id = 0
dell-base-if-cmn/set-interface/input/operation = 2
e101-026-0
Success
Key: 1.19.1245192.
base-if-phy/hardware-port/front-panel-port = 26
if/interfaces/interface/name = e101-026-0
if/interfaces/interface/type = ianaift:ethernetCsmacd
cps/object-group/return-code = 0
base-if-phy/hardware-port/subport-id = 0
dell-base-if-cmn/set-interface/input/operation = 2
root@OPX:~# opx-config-hybrid-group set hybrid-group port --name hybrid-group-13 --port-id 25 --breakout 10gx4
Namespace(breakout='10gx4', command='set', config='port', name='hybrid-group-13', phy_mode='ether', port_id='25', subcommand='hybrid-group')
e101-025-1
Success
Key: 1.19.1245192.
base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 503
dell-if/if/interfaces/interface/phys-address = 50:9a:4c:d5:ad:52
if/interfaces/interface/type = ianaift:ethernetCsmacd
if/interfaces/interface/name = e101-025-1
base-if-phy/hardware-port/front-panel-port = 25
cps/object-group/return-code = 0
base-if-phy/hardware-port/subport-id = 1
base-if-phy/if/interfaces/interface/port-id = 149
dell-base-if-cmn/set-interface/input/operation = 1
base-if-phy/if/interfaces/interface/supported-autoneg = 4
dell-if/if/interfaces/interface/negotiation = 1
e101-025-2
Success
Key: 1.19.1245192.
base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 504
dell-if/if/interfaces/interface/phys-address = 50:9a:4c:d5:ad:53
if/interfaces/interface/type = ianaift:ethernetCsmacd
if/interfaces/interface/name = e101-025-2
base-if-phy/hardware-port/front-panel-port = 25
cps/object-group/return-code = 0
base-if-phy/hardware-port/subport-id = 2
base-if-phy/if/interfaces/interface/port-id = 150
dell-base-if-cmn/set-interface/input/operation = 1
base-if-phy/if/interfaces/interface/supported-autoneg = 4
dell-if/if/interfaces/interface/negotiation = 1
e101-025-3
Success
Key: 1.19.1245192.
base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 505
dell-if/if/interfaces/interface/phys-address = 50:9a:4c:d5:ad:54
if/interfaces/interface/type = ianaift:ethernetCsmacd
if/interfaces/interface/name = e101-025-3
base-if-phy/hardware-port/front-panel-port = 25
cps/object-group/return-code = 0
base-if-phy/hardware-port/subport-id = 3
base-if-phy/if/interfaces/interface/port-id = 151
dell-base-if-cmn/set-interface/input/operation = 1
base-if-phy/if/interfaces/interface/supported-autoneg = 4
dell-if/if/interfaces/interface/negotiation = 1
e101-025-4
Success
Key: 1.19.1245192.
base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 506
dell-if/if/interfaces/interface/phys-address = 50:9a:4c:d5:ad:55
if/interfaces/interface/type = ianaift:ethernetCsmacd
if/interfaces/interface/name = e101-025-4
base-if-phy/hardware-port/front-panel-port = 25
cps/object-group/return-code = 0
base-if-phy/hardware-port/subport-id = 4
base-if-phy/if/interfaces/interface/port-id = 152
dell-base-if-cmn/set-interface/input/operation = 1
base-if-phy/if/interfaces/interface/supported-autoneg = 4
dell-if/if/interfaces/interface/negotiation = 1
root@OPX:~# 
root@OPX:~# 
root@OPX:~# 
root@OPX:~# 
root@OPX:~#  opx-config-hybrid-group set hybrid-group profile --name hybrid-group-13 --profile unrestricted
Namespace(command='set', config='profile', name='hybrid-group-13', profile='unrestricted', subcommand='hybrid-group')
e101-025-0
e101-026-0
root@OPX:~# opx-ethtool e101-025-0
 Wrong interface name or interface not present.
root@OPX:~# opx-config-hybrid-group set hybrid-group port --name hybrid-group-13 --port-id 25 --breakout 100gx1
Namespace(breakout='100gx1', command='set', config='port', name='hybrid-group-13', phy_mode='ether', port_id='25', subcommand='hybrid-group')
e101-025-1
root@OPX:~# 
root@OPX:~# 
root@OPX:~# 
root@OPX:~# 
root@OPX:~# 
root@OPX:~# opx-ethtool e101-025-0
 Wrong interface name or interface not present.
root@OPX:~# opx-ethtool e101-026-0
 Wrong interface name or interface not present.
root@OPX:~# opx-ethtool e101-025-1

 Media not present or not accessible 

Settings for e101-025-1:
    Media Type: None
    Part Number: 
    Serial Number: 
    Qualified: 
    Administrative State: DOWN
    Operational State: DOWN
    Supported Speed (in Mbps):  [100000]
    Auto Negotiation : off
    Configured Speed   : 0
    Operating Speed   : 0
    Duplex   : full
root@OPX:~# opx-ethtool e101-025-2
Traceback (most recent call last):
  File "/usr/bin/opx-ethtool", line 291, in <module>
    main(sys.argv[1:])
  File "/usr/bin/opx-ethtool", line 272, in main
    ethtool_show_interface(argv)
  File "/usr/bin/opx-ethtool", line 60, in ethtool_show_interface
    supported_speed = _if_state_obj.get_attr_data('dell-if/if/interfaces-state/interface/supported-speed')
  File "/usr/lib/opx/cps_object.py", line 338, in get_attr_data
    raise ValueError("Could not find attribute '" + attr + "' in the CPS object")
ValueError: Could not find attribute 'dell-if/if/interfaces-state/interface/supported-speed' in the CPS object
root@OPX:~# 
```

**Comment by jeff-yin** [comment]
@waliulislam is this still an issue in the OPX 3.1.0 release? At the bottom of the command documentation (https://github.com/open-switch/opx-docs/wiki/opx-config-fanout) there is an example of successful fan-in.
